#!/usr/bin/env python3
"""The entrypoint of the repository."""
from importlib import import_module
from argparse import ArgumentParser
from sys import exit as sysexit

class Parser(ArgumentParser):
    """A custom argument parser that prints the help on error."""
    def error(self, message):
        print(f"error: {message}")
        self.print_help()
        sysexit(2)

def main():
    """The entrypoint of the repository."""
    parser = Parser()
    subparsers = parser.add_subparsers(title="commands", dest="command")
    parser.add_argument("-v", "--verbose", action="store_true")

    _ = subparsers.add_parser("prepare")

    _ = subparsers.add_parser("train")

    _ = subparsers.add_parser("test")

    _ = subparsers.add_parser("infer")

    api = subparsers.add_parser("api")
    api.add_argument("-w", "--watch", action="store_true")
    api.add_argument("-p", "--port", type=int)

    _ = subparsers.add_parser("lint")

    _ = subparsers.add_parser("unit")

    args = parser.parse_args()
    if hasattr(args, "command"):
        module = import_module(f"{args.command}")
        module.main(args)
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
