#!/bin/bash
echo "#!/bin/bash" > start.command
echo "set -exo pipefail" >> start.command
echo "cd $PWD" >> start.command
echo "node -r dotenv/config --inspect ./build/app.js" >> start.command
chmod +x start.command
open ./start.command
sleep 1
rm start.command