name: 'Setup Solana SDK'
description: 'Sets up the solana sdk using the specified version'
inputs:
  version:
  description: 'The version of the solana sdk to use'
  required: false
  default: 'stable'
  key:
  description: 'The private key to use for the solana sdk'
  required: false
  cluster:
  description: 'The cluster to use for the solana sdk'
  required: false
  default: 'devnet'
runs:
  using: "composite"
  steps:
  - name: Download Solana SDK
    run: |
    curl -sSfL "https://release.solana.com/${{ inputs.version }}/install" | sh
    echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
    shell: bash
  - name: Configure Solana
    if: ${{ inputs.key }}
    run: |
    echo "${{ inputs.key }}" > solana_keypair.json
    solana config set --keypair solana_keypair.json
    solana config set --url "${{ inputs.cluster }}"
    echo "Created credentials file at $(pwd)/solana_keypair.json"
    shell: bash
  - name: Airdrop
    if: ${{ inputs.key && inputs.cluster == 'devnet' }}
    run: |
    solana airdrop 1 || true
    shell: bash
