#!/bin/bash
echo "#!/bin/bash" > start.command
echo "set -o errexit -o pipefail -o xtrace" >> start.command
echo "cd $PWD" >> start.command
for VARIABLE in $(cat ../.env | xargs); do
    echo "export $VARIABLE" >> start.command
done
echo "node --inspect ./lib/app.js" >> start.command
chmod +x start.command
open ./start.command
sleep 1
rm start.command